package com.mohaberabi.jetmart.core.presentation.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF005139)
val onPrimaryLight = Color(0xFFD2FF00)
val primaryContainerLight = Color(0xFFC0EFB0)
val onPrimaryContainerLight = Color(0xFF002200)
val secondaryLight = Color(0xFF546524)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD7EB9B)
val onSecondaryContainerLight = Color(0xFF161F00)
val tertiaryLight = Color(0xFF386568)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBCEBEE)
val onTertiaryContainerLight = Color(0xFF002022)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8FBF1)
val onBackgroundLight = Color(0xFF191D17)
val surfaceLight = Color(0xFFF8FBF1)
val onSurfaceLight = Color(0xFF191D17)
val surfaceVariantLight = Color(0xFFDFE4D7)
val onSurfaceVariantLight = Color(0xFF43483F)
val outlineLight = Color(0xFF73796E)
val outlineVariantLight = Color(0xFFC3C8BC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E322B)
val inverseOnSurfaceLight = Color(0xFFEFF2E8)
val inversePrimaryLight = Color(0xFFA5D396)
val surfaceDimLight = Color(0xFFD8DBD2)
val surfaceBrightLight = Color(0xFFF8FBF1)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F5EB)
val surfaceContainerLight = Color(0xFFECEFE5)
val surfaceContainerHighLight = Color(0xFFE6E9E0)
val surfaceContainerHighestLight = Color(0xFFE1E4DA)

